### ISSUE TITLE
[FEATURE] Use configuration from query file header

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/lsql#114]
A user can define configuration parameters in the [query header](https://github.com/databrickslabs/lsql/blob/main/docs/dashboards.md#headers-of-sql-files). The configuration is stated in the commented lines in the header.

**Comment by JCZuurmond** [comment]
@nfx : Have you settled on a preferred format for the configuration? I am leaning towards argparse:

```
-- --width 10 --height 3
```

```
*/
--width 10 --height 3
/*  
```

IMO json is to verbose and yaml covers too many lines. Also, I prefer argparse over custom parsing like the one in ucx

**Comment by nfx** [comment]
@JCZuurmond let's go with argparse, it's good enough for what we need. `/* --width 10 --height 3 */`
